### ISSUE TITLE
release numpy.float fixes

### ISSUE THREAD

**Issue by bmegli** [crigroup/baldor#8]
Hi @fsuarez6,

I am asking you as the author and official maintainer of the package.

Could the #7 fixes be released (bump `package.xml` version, bloom)?

With the removal of deprecated attributes in numpy, dependent ROS packages will now fail at runtime in noetic with updated numpy (e.g. pip version).

Some examples:
- https://github.com/ros-planning/moveit_calibration/issues/133
- https://github.com/crigroup/handeye
- ...

Kind regards

--------------------

Edit:
- clarified when the problem happens

**Comment by fsuarez6** [comment]
I've reverted #7 and will work on a proper fix so that we don't break previous ROS packages

**Comment by bmegli** [comment]
For reference:
- deprecated
  - https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated
- expired
  - https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations

**Comment by bmegli** [comment]
Also, the problem may not happen on clean Focal + Noetic.

The `apt` numpy version is 17.4 (before deprecation and expiry). 

```bash
apt-cache policy python3-numpy
python3-numpy:
  Installed: 1:1.17.4-5ubuntu3.1
  Candidate: 1:1.17.4-5ubuntu3.1
```

So the problem stems from something else updating numpy through pip and overriding system version.
(for general public)

**Comment by bmegli** [comment]
@fsuarez6, I am fine to close this issue.

After investigation:
- clean Focal + Noetic should have older version of numpy that doesn't have this problem
- problem is caused by pip installed numpy >= 1. 24.0

You may still want to figure out forward and backward compatible solution but this is not urgent.
